fixtures:
  repositories:
    common:
      repo: 'https://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.4.1'
    rpcbind:
      repo: 'https://github.com/ghoneycutt/puppet-module-rpcbind.git'
      ref: 'v1.0.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    types:
      repo: 'https://github.com/ghoneycutt/puppet-module-types.git'
      ref: 'v1.1.0'
  symlinks:
    nfs: "#{source_dir}"
